version = 0.1
[default.deploy.parameters]
stack_name = "test-java-stack"
resolve_s3 = true
s3_prefix = "test-java-stack"
region = "ap-northeast-1"
profile = "aws-semi"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
