AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: example.Handler::handleRequest
      Runtime: java11
      Architectures:
      - x86_64
      Timeout: 30
      MemorySize: 512
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId:
              Ref: SampleAPI

  SampleAPI:
     Type: AWS::Serverless::Api
     Properties:
       Name: sample_api
       StageName: development
       EndpointConfiguration: REGIONAL
