AWSTemplateFormatVersion: '2010-09-09'
Description: S3 and CloudFront with OAI for front-end hosting

Resources:
  S3FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'nap-frontend'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
