AWSTemplateFormatVersion: '2010-09-09'
Description: S3 and CloudFront with OAI for front-end hosting

Resources:
  S3FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'nap-frontend'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${FrontendCloudFrontOAI}"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${S3FrontendBucket}/*"

  FrontendCloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for S3 Frontend Bucket

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3FrontendBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${FrontendCloudFrontOAI}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        DefaultRootObject: index.html
#        ViewerCertificate:
#          CloudFrontDefaultCertificate: true
